# Generated by Django 6.1 on 2026-08-07 13:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reference",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("date", models.DateField(verbose_name="Dato")),
                ("start_time", models.TimeField(verbose_name="Starttid")),
                ("end_time", models.TimeField(verbose_name="Sluttid")),
                (
                    "customer_name",
                    models.CharField(max_length=120, verbose_name="Navn"),
                ),
                (
                    "customer_phone",
                    models.CharField(max_length=30, verbose_name="Telefon"),
                ),
                (
                    "customer_email",
                    models.EmailField(max_length=254, verbose_name="E-post"),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Merknad")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Venter på betaling"),
                            ("confirmed", "Bekreftet"),
                            ("cancelled", "Kansellert"),
                            ("completed", "Fullført"),
                        ],
                        default="pending_payment",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookinger",
                "ordering": ["date", "start_time"],
            },
        ),
        migrations.CreateModel(
            name="BusinessHours",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Mandag"),
                            (1, "Tirsdag"),
                            (2, "Onsdag"),
                            (3, "Torsdag"),
                            (4, "Fredag"),
                            (5, "Lørdag"),
                            (6, "Søndag"),
                        ],
                        unique=True,
                        verbose_name="Ukedag",
                    ),
                ),
                (
                    "is_closed",
                    models.BooleanField(
                        default=False, verbose_name="Stengt denne dagen"
                    ),
                ),
                ("open_time", models.TimeField(default="08:00", verbose_name="Åpner")),
                (
                    "close_time",
                    models.TimeField(default="18:00", verbose_name="Stenger"),
                ),
            ],
            options={
                "verbose_name": "Åpningstid",
                "verbose_name_plural": "Åpningstider",
                "ordering": ["weekday"],
            },
        ),
        migrations.CreateModel(
            name="ClosedDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="Dato")),
                (
                    "reason",
                    models.CharField(blank=True, max_length=200, verbose_name="Årsak"),
                ),
            ],
            options={
                "verbose_name": "Stengt dato",
                "verbose_name_plural": "Stengte datoer",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Navn")),
                (
                    "slug",
                    models.SlugField(
                        max_length=110, unique=True, verbose_name="URL-navn"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Beskrivelse"),
                ),
                ("price_kr", models.PositiveIntegerField(verbose_name="Pris (kr)")),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=60,
                        help_text="Hvor lang tid tar denne tjenesten? Styrer ledige tider i bookingkalenderen.",
                        verbose_name="Varighet (minutter)",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="services/",
                        verbose_name="Bilde",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Aktiv (vises på nettsiden)"
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Rekkefølge"),
                ),
            ],
            options={
                "verbose_name": "Tjeneste",
                "verbose_name_plural": "Tjenester",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "business_name",
                    models.CharField(default="Florø Detailing", max_length=120),
                ),
                (
                    "phone",
                    models.CharField(
                        default="+47 483 03 985", max_length=30, verbose_name="Telefon"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="E-post"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        default="Florø", max_length=200, verbose_name="Adresse/sted"
                    ),
                ),
                (
                    "instagram_url",
                    models.URLField(blank=True, verbose_name="Instagram"),
                ),
                ("facebook_url", models.URLField(blank=True, verbose_name="Facebook")),
                (
                    "hero_heading",
                    models.CharField(
                        default="Din bil fortjener det beste", max_length=150
                    ),
                ),
                (
                    "hero_subheading",
                    models.CharField(
                        default="Profesjonell bilvask og detailing i Florø. Book time på under ett minutt.",
                        max_length=250,
                    ),
                ),
                (
                    "about_text",
                    models.TextField(
                        blank=True,
                        default="Florø Detailing tilbyr grundig og skånsom bilvask og detailing for folk i Florø-området. Vi behandler hver bil som om det var vår egen.",
                    ),
                ),
                (
                    "simultaneous_capacity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Hvor mange biler kan vaskes/behandles på samme tid (antall vaskeplasser).",
                        verbose_name="Antall biler samtidig",
                    ),
                ),
                (
                    "booking_lead_time_hours",
                    models.PositiveIntegerField(
                        default=2,
                        help_text="Kunder kan ikke booke en tid som er nærmere enn dette.",
                        verbose_name="Minste varsel før booking (timer)",
                    ),
                ),
                (
                    "booking_horizon_days",
                    models.PositiveIntegerField(
                        default=30, verbose_name="Hvor mange dager frem kan det bookes"
                    ),
                ),
                (
                    "require_online_payment",
                    models.BooleanField(
                        default=True,
                        help_text="Hvis av, bookes timen uten betaling (bekreftes manuelt/betales på stedet).",
                        verbose_name="Krev Vipps-betaling ved booking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nettsideinnstilling",
                "verbose_name_plural": "Nettsideinnstillinger",
            },
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vipps_reference", models.CharField(max_length=64, unique=True)),
                (
                    "amount_ore",
                    models.PositiveIntegerField(
                        help_text="Beløp i øre (400 kr = 40000)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Opprettet"),
                            ("AUTHORIZED", "Godkjent"),
                            ("CAPTURED", "Betalt (belastet)"),
                            ("CANCELLED", "Kansellert"),
                            ("FAILED", "Feilet"),
                            ("TERMINATED", "Avbrutt av kunde"),
                        ],
                        default="CREATED",
                        max_length=20,
                    ),
                ),
                ("raw_last_event", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="booking.booking",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="booking",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="booking.service",
                verbose_name="Tjeneste",
            ),
        ),
    ]
