# Generated by Django 6.1 on 2026-08-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0003_remove_vipps_payments"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="E-post")),
                ("code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Verifisert"
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                "verbose_name": "E-postverifisering",
                "verbose_name_plural": "E-postverifiseringer",
                "ordering": ["-created_at"],
            },
        ),
    ]
