# Generated by Django 6.1 on 2026-08-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0006_weekday_hours_closed_weekends"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="customer_phone",
            field=models.CharField(blank=True, max_length=30, verbose_name="Telefon"),
        ),
    ]
