# Generated by Django 6.1 on 2026-08-17 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0007_alter_booking_customer_phone"),
    ]

    operations = [
        migrations.RemoveField(model_name="booking", name="customer_phone",),
    ]
